### ISSUE TITLE
License

### ISSUE THREAD

**Issue by medasx** [aaaton/golem#6]
Could you add license to your repo ?

**Comment by aaaton** [comment]
I added an MIT license

Run wild and free

**Comment by aaaton** [comment]
That being said, please note that Golem is based on [lexiconista](https://github.com/michmech/lemmatization-lists/) which has an Open Database license (ODbL). 

I'm actually not sure if I can set an MIT License on the entire project, but ODbL also allows commercial use from what I understand.
